"""
Unicode symbol and shape constants for use in terminal output and text processing.
All constants are uppercase following Python naming conventions.
"""

# Box drawing - single line
BOX_SINGLE_HORIZONTAL = "─"
BOX_SINGLE_VERTICAL = "│"
BOX_SINGLE_TOP_LEFT = "┌"
BOX_SINGLE_TOP_RIGHT = "┐"
BOX_SINGLE_BOTTOM_LEFT = "└"
BOX_SINGLE_BOTTOM_RIGHT = "┘"
BOX_SINGLE_VERTICAL_LEFT = "├"
BOX_SINGLE_VERTICAL_RIGHT = "┤"
BOX_SINGLE_HORIZONTAL_DOWN = "┬"
BOX_SINGLE_HORIZONTAL_UP = "┴"
BOX_SINGLE_CROSS = "┼"

# Box drawing - double line
BOX_DOUBLE_HORIZONTAL = "═"
BOX_DOUBLE_VERTICAL = "║"
BOX_DOUBLE_TOP_LEFT = "╔"
BOX_DOUBLE_TOP_RIGHT = "╗"
BOX_DOUBLE_BOTTOM_LEFT = "╚"
BOX_DOUBLE_BOTTOM_RIGHT = "╝"
BOX_DOUBLE_VERTICAL_LEFT = "╠"
BOX_DOUBLE_VERTICAL_RIGHT = "╣"
BOX_DOUBLE_HORIZONTAL_DOWN = "╦"
BOX_DOUBLE_HORIZONTAL_UP = "╩"
BOX_DOUBLE_CROSS = "╬"

# Box drawing - mixed
BOX_SINGLE_DOUBLE_HORIZONTAL = "╤"
BOX_SINGLE_DOUBLE_VERTICAL = "╢"
BOX_DOUBLE_SINGLE_HORIZONTAL = "╥"
BOX_DOUBLE_SINGLE_VERTICAL = "╡"
BOX_SINGLE_DOUBLE_TOP_LEFT = "╓"
BOX_SINGLE_DOUBLE_TOP_RIGHT = "╖"
BOX_SINGLE_DOUBLE_BOTTOM_LEFT = "╙"
BOX_SINGLE_DOUBLE_BOTTOM_RIGHT = "╜"
BOX_DOUBLE_SINGLE_TOP_LEFT = "╒"
BOX_DOUBLE_SINGLE_TOP_RIGHT = "╕"
BOX_DOUBLE_SINGLE_BOTTOM_LEFT = "╘"
BOX_DOUBLE_SINGLE_BOTTOM_RIGHT = "╛"



# Geometric shapes - squares
SQUARE_BLACK = "■"
SQUARE_WHITE = "□"
SQUARE_WHITE_WITH_ROUNDED_CORNERS = "▢"
SQUARE_BLACK_SMALL = "▪"
SQUARE_WHITE_SMALL = "▫"
SQUARE_BLACK_MEDIUM = "◼"
SQUARE_WHITE_MEDIUM = "◻"
SQUARE_BLACK_LARGE = "⬛"
SQUARE_WHITE_LARGE = "⬜"

# Geometric shapes - circles
CIRCLE_BLACK = "●"
CIRCLE_WHITE = "○"
CIRCLE_BLACK_SMALL = "•"
CIRCLE_WHITE_SMALL = "◦"
CIRCLE_BLACK_MEDIUM = "◼"
CIRCLE_WHITE_MEDIUM = "◻"
CIRCLE_BLACK_LARGE = "⬛"
CIRCLE_WHITE_LARGE = "⬜"
CIRCLE_DOT = "⚫"
CIRCLE_DOT_WHITE = "⚪"

# Geometric shapes - triangles
TRIANGLE_UP = "▲"
TRIANGLE_DOWN = "▼"
TRIANGLE_LEFT = "◄"
TRIANGLE_RIGHT = "►"
TRIANGLE_UP_WHITE = "△"
TRIANGLE_DOWN_WHITE = "▽"
TRIANGLE_LEFT_WHITE = "◁"
TRIANGLE_RIGHT_WHITE = "▷"
TRIANGLE_UP_BLACK = "▲"
TRIANGLE_DOWN_BLACK = "▼"
TRIANGLE_LEFT_BLACK = "◄"
TRIANGLE_RIGHT_BLACK = "►"

# Geometric shapes - diamonds
DIAMOND_BLACK = "◆"
DIAMOND_WHITE = "◇"
DIAMOND_BLACK_SMALL = "♦"
DIAMOND_WHITE_SMALL = "♢"

# Lines and pipes
PIPE_VERTICAL = "│"
PIPE_VERTICAL_THICK = "┃"
PIPE_VERTICAL_DOUBLE = "║"
PIPE_HORIZONTAL = "─"
PIPE_HORIZONTAL_THICK = "━"
PIPE_HORIZONTAL_DOUBLE = "═"
PIPE_THIN_VERTICAL = "│"
PIPE_THIN_HORIZONTAL = "─"

# Arrows - simple
ARROW_UP = "↑"
ARROW_DOWN = "↓"
ARROW_LEFT = "←"
ARROW_RIGHT = "→"
ARROW_UP_DOWN = "↕"
ARROW_LEFT_RIGHT = "↔"
ARROW_UP_LEFT = "↖"
ARROW_UP_RIGHT = "↗"
ARROW_DOWN_LEFT = "↙"
ARROW_DOWN_RIGHT = "↘"

# Arrows - double
ARROW_DOUBLE_UP = "⇑"
ARROW_DOUBLE_DOWN = "⇓"
ARROW_DOUBLE_LEFT = "⇐"
ARROW_DOUBLE_RIGHT = "⇒"
ARROW_DOUBLE_UP_DOWN = "⇕"
ARROW_DOUBLE_LEFT_RIGHT = "⇔"

# Arrows - curved
ARROW_CURVED_UP = "↶"
ARROW_CURVED_DOWN = "↷"
ARROW_CURVED_LEFT = "↺"
ARROW_CURVED_RIGHT = "↻"
ARROW_CURVED_UP_LEFT = "↰"
ARROW_CURVED_UP_RIGHT = "↱"
ARROW_CURVED_DOWN_LEFT = "↲"
ARROW_CURVED_DOWN_RIGHT = "↳"

# Mathematical symbols
PLUS = "＋"
MINUS = "－"
MULTIPLY = "×"
DIVIDE = "÷"
EQUALS = "＝"
NOT_EQUALS = "≠"
LESS_THAN = "＜"
GREATER_THAN = "＞"
LESS_THAN_OR_EQUAL = "≤"
GREATER_THAN_OR_EQUAL = "≥"
APPROXIMATELY = "≈"
INFINITY = "∞"
SUM = "∑"
PRODUCT = "∏"
INTEGRAL = "∫"
PARTIAL_DERIVATIVE = "∂"
NABLA = "∇"
SQUARE_ROOT = "√"
CUBE_ROOT = "∛"
FOURTH_ROOT = "∜"
PI = "π"
TAU = "τ"
SIGMA = "σ"
DELTA = "Δ"
ALPHA = "α"
BETA = "β"
GAMMA = "γ"
THETA = "θ"
LAMBDA = "λ"
MU = "μ"
OMEGA = "Ω"

# Set theory
ELEMENT_OF = "∈"
NOT_ELEMENT_OF = "∉"
SUBSET_OF = "⊂"
SUPERSET_OF = "⊃"
UNION = "∪"
INTERSECTION = "∩"
EMPTY_SET = "∅"

# Logic symbols
AND = "∧"
OR = "∨"
NOT = "¬"
IMPLIES = "⇒"
IFF = "⇔"
FOR_ALL = "∀"
THERE_EXISTS = "∃"
THEREFORE = "∴"
BECAUSE = "∵"

# Currency symbols
DOLLAR = "$"
CENT = "¢"
POUND = "£"
YEN = "¥"
EURO = "€"
RUPEE = "₹"
WON = "₩"
RUBLE = "₽"
LIRA = "₺"
FRANC = "₣"
PESO = "₱"
DONG = "₫"
MANAT = "₼"
TENGE = "₸"
HRYVNIA = "₴"
SHEQEL = "₪"
BAHT = "฿"
NAIRA = "₦"
GUARANI = "₲"
CRUZEIRO = "₢"
FRENCH_FRANC = "₣"
LIRA2 = "₤"
MILL = "₥"
PESETA = "₧"
DRACHMA = "₯"
GERMAN_PENNY = "₰"
PESO2 = "₱"
SPECIAL = "₨"
WON2 = "₩"
SHEQEL2 = "₪"
NEW_SHEQEL = "₪"
DONG2 = "₫"
KIP = "₭"
TUGRIK = "₮"
DRACHMA2 = "₯"
EURO2 = "€"
COLON = "₡"
CRUZEIRO2 = "₢"
FRENCH_FRANC2 = "₣"
LIRA3 = "₤"
MILL2 = "₥"
NAIRA2 = "₦"
PESETA2 = "₧"
RUPEE2 = "₨"
WON3 = "₩"
NEW_SHEQEL2 = "₪"
DONG3 = "₫"
KIP2 = "₭"
TUGRIK2 = "₮"
DRACHMA3 = "₯"
EURO3 = "€"
EURO_CENT = "¢"

# Fractions
FRACTION_ONE_HALF = "½"
FRACTION_ONE_THIRD = "⅓"
FRACTION_TWO_THIRDS = "⅔"
FRACTION_ONE_QUARTER = "¼"
FRACTION_THREE_QUARTERS = "¾"
FRACTION_ONE_FIFTH = "⅕"
FRACTION_TWO_FIFTHS = "⅖"
FRACTION_THREE_FIFTHS = "⅗"
FRACTION_FOUR_FIFTHS = "⅘"
FRACTION_ONE_SIXTH = "⅙"
FRACTION_FIVE_SIXTHS = "⅚"
FRACTION_ONE_EIGHTH = "⅛"
FRACTION_THREE_EIGHTHS = "⅜"
FRACTION_FIVE_EIGHTHS = "⅝"
FRACTION_SEVEN_EIGHTHS = "⅞"

# Superscripts
SUPERSCRIPT_ONE = "¹"
SUPERSCRIPT_TWO = "²"
SUPERSCRIPT_THREE = "³"
SUPERSCRIPT_FOUR = "⁴"
SUPERSCRIPT_FIVE = "⁵"
SUPERSCRIPT_SIX = "⁶"
SUPERSCRIPT_SEVEN = "⁷"
SUPERSCRIPT_EIGHT = "⁸"
SUPERSCRIPT_NINE = "⁹"
SUPERSCRIPT_ZERO = "⁰"
SUPERSCRIPT_PLUS = "⁺"
SUPERSCRIPT_MINUS = "⁻"
SUPERSCRIPT_EQUALS = "⁼"
SUPERSCRIPT_LEFT_PARENTHESIS = "⁽"
SUPERSCRIPT_RIGHT_PARENTHESIS = "⁾"
SUPERSCRIPT_N = "ⁿ"
SUPERSCRIPT_I = "ⁱ"

# Subscripts
SUBSCRIPT_ZERO = "₀"
SUBSCRIPT_ONE = "₁"
SUBSCRIPT_TWO = "₂"
SUBSCRIPT_THREE = "₃"
SUBSCRIPT_FOUR = "₄"
SUBSCRIPT_FIVE = "₅"
SUBSCRIPT_SIX = "₆"
SUBSCRIPT_SEVEN = "₇"
SUBSCRIPT_EIGHT = "₈"
SUBSCRIPT_NINE = "₉"
SUBSCRIPT_PLUS = "₊"
SUBSCRIPT_MINUS = "₋"
SUBSCRIPT_EQUALS = "₌"
SUBSCRIPT_LEFT_PARENTHESIS = "₍"
SUBSCRIPT_RIGHT_PARENTHESIS = "₎"
SUBSCRIPT_A = "ₐ"
SUBSCRIPT_E = "ₑ"
SUBSCRIPT_H = "ₕ"
SUBSCRIPT_I = "ᵢ"
SUBSCRIPT_J = "ⱼ"
SUBSCRIPT_K = "ₖ"
SUBSCRIPT_L = "ₗ"
SUBSCRIPT_M = "ₘ"
SUBSCRIPT_N = "ₙ"
SUBSCRIPT_O = "ₒ"
SUBSCRIPT_P = "ₚ"
SUBSCRIPT_R = "ᵣ"
SUBSCRIPT_S = "ₛ"
SUBSCRIPT_T = "ₜ"
SUBSCRIPT_U = "ᵤ"
SUBSCRIPT_V = "ᵥ"
SUBSCRIPT_X = "ₓ"

# Musical symbols
MUSICAL_NOTE = "♪"
MUSICAL_NOTES = "♫"
MUSICAL_CLEF = "♭"
MUSICAL_SHARP = "♯"
MUSICAL_FLAT = "♭"
MUSICAL_NATURAL = "♮"
MUSICAL_DOUBLE_SHARP = "𝄪"
MUSICAL_DOUBLE_FLAT = "𝄫"

# Card suits
SPADE = "♠"
HEART = "♥"
DIAMOND = "♦"
CLUB = "♣"
SPADE_WHITE = "♤"
HEART_WHITE = "♡"
DIAMOND_WHITE = "♢"
CLUB_WHITE = "♧"

# Chess pieces
CHESS_KING_WHITE = "♔"
CHESS_QUEEN_WHITE = "♕"
CHESS_ROOK_WHITE = "♖"
CHESS_BISHOP_WHITE = "♗"
CHESS_KNIGHT_WHITE = "♘"
CHESS_PAWN_WHITE = "♙"
CHESS_KING_BLACK = "♚"
CHESS_QUEEN_BLACK = "♛"
CHESS_ROOK_BLACK = "♜"
CHESS_BISHOP_BLACK = "♝"
CHESS_KNIGHT_BLACK = "♞"
CHESS_PAWN_BLACK = "♟"

# Weather and nature symbols
SUN = "☀"
CLOUD = "☁"
UMBRELLA = "☂"
SNOWMAN = "☃"
COMET = "☄"
STAR = "⭐"
STAR_BLACK = "★"
STAR_WHITE = "☆"
LIGHTNING = "⚡"
SNOWFLAKE = "❄"
FIRE = "🔥"
DROPLET = "💧"
WATER_WAVE = "🌊"

# Miscellaneous symbols
COPYRIGHT = "©"
REGISTERED = "®"
TRADEMARK = "™"
DEGREE = "°"
PRIME = "′"
DOUBLE_PRIME = "″"
TRIPLE_PRIME = "‴"
QUADRUPLE_PRIME = "⁗"
SECTION = "§"
PARAGRAPH = "¶"
BULLET = "•"
MIDDLE_DOT = "·"
ELLIPSIS = "…"
EN_DASH = "–"
EM_DASH = "—"
LEFT_SINGLE_QUOTE = "\u2018"
RIGHT_SINGLE_QUOTE = "\u2019"
LEFT_DOUBLE_QUOTE = "\u201C"
RIGHT_DOUBLE_QUOTE = "\u201D"
LEFT_SINGLE_QUOTE2 = "\u201A"
RIGHT_SINGLE_QUOTE2 = "\u2019"
LEFT_DOUBLE_QUOTE2 = "\u201E"
RIGHT_DOUBLE_QUOTE2 = "\u201D"
LEFT_SINGLE_QUOTE3 = "\u2039"
RIGHT_SINGLE_QUOTE3 = "\u203A"
LEFT_DOUBLE_QUOTE3 = "\u00AB"
RIGHT_DOUBLE_QUOTE3 = "\u00BB"

# Brackets and parentheses
LEFT_PARENTHESIS = "("
RIGHT_PARENTHESIS = ")"
LEFT_BRACKET = "["
RIGHT_BRACKET = "]"
LEFT_BRACE = "{"
RIGHT_BRACE = "}"
LEFT_ANGLE = "<"
RIGHT_ANGLE = ">"
LEFT_DOUBLE_ANGLE = "«"
RIGHT_DOUBLE_ANGLE = "»"
LEFT_FLOOR = "⌊"
RIGHT_FLOOR = "⌋"
LEFT_CEILING = "⌈"
RIGHT_CEILING = "⌉"

# Technical symbols
CHECK_MARK = "✓"
CHECK_MARK_BOLD = "✔"
CROSS_MARK = "✗"
CROSS_MARK_BOLD = "✘"
MULTIPLY2 = "✕"
MULTIPLY3 = "✖"
HEAVY_MULTIPLY = "✖"
PLUS2 = "✚"
HEAVY_PLUS = "➕"
MINUS2 = "➖"
HEAVY_MINUS = "➖"
DIVIDE2 = "➗"
HEAVY_DIVIDE = "➗"
EQUALS2 = "═"
HEAVY_EQUALS = "🟰"

# Stars and asterisks
ASTERISK = "*"
ASTERISK_EIGHT_SPOKED = "✳"
ASTERISK_EIGHT_POINTED = "✴"
ASTERISK_SIXTEEN_POINTED = "✶"
STAR_FOUR_POINTED = "✦"
STAR_FOUR_POINTED_BLACK = "✦"
STAR_FIVE_POINTED = "★"
STAR_FIVE_POINTED_WHITE = "☆"
STAR_SIX_POINTED = "✶"
STAR_EIGHT_POINTED = "✴"
STAR_TWELVE_POINTED = "✹"
STAR_SIXTEEN_POINTED = "✶"

# Arrows - additional
ARROW_LEFT_RIGHT2 = "↔"
ARROW_UP_DOWN2 = "↕"
ARROW_NORTH_WEST = "↖"
ARROW_NORTH_EAST = "↗"
ARROW_SOUTH_EAST = "↘"
ARROW_SOUTH_WEST = "↙"
ARROW_NORTH = "↑"
ARROW_SOUTH = "↓"
ARROW_EAST = "→"
ARROW_WEST = "←"
ARROW_NORTH_WEST2 = "↖"
ARROW_NORTH_EAST2 = "↗"
ARROW_SOUTH_EAST2 = "↘"
ARROW_SOUTH_WEST2 = "↙"

# Zodiac symbols
ARIES = "♈"
TAURUS = "♉"
GEMINI = "♊"
CANCER = "♋"
LEO = "♌"
VIRGO = "♍"
LIBRA = "♎"
SCORPIUS = "♏"
SAGITTARIUS = "♐"
CAPRICORN = "♑"
AQUARIUS = "♒"
PISCES = "♓"
OPHIUCHUS = "⛎"

# Religious symbols
CROSS_LATIN = "✝"
CROSS_ORTHODOX = "☦"
STAR_AND_CRESCENT = "☪"
PEACE = "☮"
YIN_YANG = "☯"
OM = "ॐ"
STAR_OF_DAVID = "✡"
WHEEL_OF_DHARMA = "☸"
FARSI = "☫"

# Warning and safety
RADIOACTIVE = "☢"
BIOHAZARD = "☣"
WARNING = "⚠"
HIGH_VOLTAGE = "⚡"

# Time and clock
CLOCK_FACE_ONE = "🕐"
CLOCK_FACE_TWO = "🕑"
CLOCK_FACE_THREE = "🕒"
CLOCK_FACE_FOUR = "🕓"
CLOCK_FACE_FIVE = "🕔"
CLOCK_FACE_SIX = "🕕"
CLOCK_FACE_SEVEN = "🕖"
CLOCK_FACE_EIGHT = "🕗"
CLOCK_FACE_NINE = "🕘"
CLOCK_FACE_TEN = "🕙"
CLOCK_FACE_ELEVEN = "🕚"
CLOCK_FACE_TWELVE = "🕛"

# Additional geometric shapes
PENTAGON = "⬟"
HEXAGON = "⬡"
OCTAGON = "⯄"
DIAMOND2 = "⬟"
SQUARE2 = "⬜"
CIRCLE2 = "⬤"
TRIANGLE2 = "▲"
STAR2 = "★"

# Braille patterns (sample)
BRAILLE_BLANK = "⠀"
BRAILLE_DOT_0 = "⠀"
BRAILLE_DOT_1 = "⠁"
BRAILLE_DOT_2 = "⠂"
BRAILLE_DOT_3 = "⠄"
BRAILLE_DOT_4 = "⠈"
BRAILLE_DOT_5 = "⠐"
BRAILLE_DOT_6 = "⠠"
BRAILLE_DOT_7 = "⡀"  # DOTS-7  (U+2840)
BRAILLE_DOT_8 = "⢀"  # DOTS-8  (U+2880)
BRAILLE_DOTS_1_2 = "⠃"
BRAILLE_DOTS_1_3 = "⠅"
BRAILLE_DOTS_1_4 = "⠉"
BRAILLE_DOTS_1_5 = "⠑"
BRAILLE_DOTS_1_6 = "⠡"
BRAILLE_DOTS_1_7 = "⡁"
BRAILLE_DOTS_1_8 = "⢁"
BRAILLE_DOTS_2_3 = "⠆"
BRAILLE_DOTS_2_4 = "⠊"
BRAILLE_DOTS_2_5 = "⠒"
BRAILLE_DOTS_2_6 = "⠢"
BRAILLE_DOTS_2_7 = "⡂"
BRAILLE_DOTS_2_8 = "⢂"
BRAILLE_DOTS_3_4 = "⠌"
BRAILLE_DOTS_3_5 = "⠔"
BRAILLE_DOTS_3_6 = "⠤"
BRAILLE_DOTS_3_7 = "⡄"
BRAILLE_DOTS_3_8 = "⢄"
BRAILLE_DOTS_4_5 = "⠘"
BRAILLE_DOTS_4_6 = "⠨"
BRAILLE_DOTS_4_7 = "⡈"
BRAILLE_DOTS_4_8 = "⢈"
BRAILLE_DOTS_5_6 = "⠰"
BRAILLE_DOTS_5_7 = "⡐"
BRAILLE_DOTS_5_8 = "⢐"
BRAILLE_DOTS_6_7 = "⡠"
BRAILLE_DOTS_6_8 = "⢠"
BRAILLE_DOTS_7_8 = "⡀"
BRAILLE_FULL = "⣿"


Q_TL = "▘"
Q_TR = "▝"
Q_BL = "▖"
Q_BR = "▗"
Q_T = "▀"
Q_B = "▄"
Q_L = "▌"
Q_R = "▐"
Q_BLTR="▞"
Q_TLBR = "▚"
Q_NBR = "▛"
Q_NBL = "▜"
Q_NTL = "▟"
Q_NTR = "▙"
Q_F = "█"
B_1_8      = "▁"
B_2_8      = "▂"
B_3_8      = "▃"
B_4_8      = "▄"
B_5_8      = "▅"
B_6_8      = "▆"
B_7_8      = "▇"
B_FULL     = "█"
T_1_8       = "▔"
SH_1 = "░"
SH_2 =  "▒"
SH_3 = "▓"
SH_4 = "█"

BLOCK_UPPER_ONE_EIGHTH = "▁"
BLOCK_UPPER_ONE_QUARTER = "▂"
BLOCK_UPPER_THREE_EIGHTHS = "▃"
BLOCK_UPPER_HALF2 = "▄"
BLOCK_UPPER_FIVE_EIGHTHS = "▅"
BLOCK_UPPER_THREE_QUARTERS = "▆"
BLOCK_UPPER_SEVEN_EIGHTHS = "▇"
BLOCK_FULL2 = "█"
BLOCK_LOWER_ONE_EIGHTH = "▁"
BLOCK_LOWER_ONE_QUARTER = "▂"
BLOCK_LOWER_THREE_EIGHTHS = "▃"
BLOCK_LOWER_FIVE_EIGHTHS = "▅"
BLOCK_LOWER_THREE_QUARTERS = "▆"
BLOCK_LOWER_SEVEN_EIGHTHS = "▇"
BLOCK_LIGHT_SHADE = "░"
BLOCK_MEDIUM_SHADE = "▒"
BLOCK_DARK_SHADE = "▓"
BLOCK_FULL3 = "█"